/*************************
 * DO NOT EDIT THIS FILE *
 *************************/
package io.polyhx.lhgames.service;

import com.microsoft.signalr.HubConnection;
import com.microsoft.signalr.HubConnectionBuilder;
import io.polyhx.lhgames.App;

public class LHAPIService {
    private static LHAPIService INSTANCE;

    private HubConnection fHubConnection;

    private LHAPIService() { }

    public static LHAPIService getInstance() {
        if(INSTANCE == null) {
            INSTANCE = new LHAPIService();
        }

        return INSTANCE;
    }

    public void start() {
        if(fHubConnection != null) {
            System.out.println("lhapi: service is already started");
            return;
        }

        fHubConnection = HubConnectionBuilder.create(App.LHAPI_URL + "/teamshub").build();
        fHubConnection.on("AssignGameServerUriToGameId", this::onAssignGameServerUriToGameId, String.class);
        fHubConnection.start().doOnComplete(this::onConnect).subscribe();
    }

    private void onAssignGameServerUriToGameId(String uri) {
        App.GAME_SERVER_URL = uri;
        GameServerService.getInstance().start();
    }

    private void onConnect() {
        fHubConnection.send("Register", System.getenv("TEAM_ID"), System.getenv("GAME_ID"));
        System.out.println("lhapi: connection opened and handshake received");
    }
}